accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, PasswordChangeDoneView 
from .forms import LoginForm
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('login/', views.CustomLoginView.as_view(redirect_authenticated_user=True, template_name='registration/login.html',  authentication_form=LoginForm), name='login'), 
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_reset/', views.CustomPasswordResetView.as_view(), name='password_reset'), 
    path("password_reset/done/",  views.CustomPasswordResetDoneView.as_view(), name="password_reset_done" ),
    path("reset/<uidb64>/<token>/", views.CustomPasswordResetConfirmView.as_view(),  name="password_reset_confirm" ),
    path("reset/done/", views.CustomPasswordResetCompleteView.as_view(),  name="password_reset_complete", ),
    path('activate/<uidb64>/<token>/',views.activate, name='activate'),   
    path('settings/', views.profile_setting, name='profile_setting'), 
    path('dashboard/', views.DashboardView.as_view(), name='user_dashboard'), 
    path('orders/', views.OrdersView.as_view(), name='user_orders'), 
    path('due-orders/', views.DueOrdersView.as_view(), name='due_orders'), 
    path('incomplete-orders/', views.IncompleteOrdersView.as_view(), name='incomplete_orders'), 
    
    path('projects/', views.DashboardView.as_view(), name='user_projects'), 
    path('recent-activities/', views.RecentActivityView.as_view(), name='user_recents_activity'), 
    path('recent-comments/', views.RecentCommentsView.as_view(), name='user_recents_comments'), 
    path('expert-profiles/', views.ExpertiseProfile.as_view(), name='expert_profiles'), 
    path('expert-profiles/<uuid:profile_id>/edit/', views.ExpertiseProfile.as_view(), name='edit_expert_profile'),
    path('expert-profiles/<uuid:profile_id>/delete/', views.ExpertiseProfile.as_view(), name='delete_expert_profile'),
    
    path('verification-request/', views.VerificationRequest.as_view(), name='verification_request'), 
    # path('verification/<uuid:verification_request_id>/<str:image_type>/', views.serve_image, name='serve_verification_image'),
    
    path('submit-approval-request/<uuid:profile_id>/', views.SubmitApprovalRequest.as_view(), name='submit_approval_request'),
    path('delete-approval-request/<uuid:profile_id>/<int:request_id>/delete', views.SubmitApprovalRequest.as_view(), name='delete_approval_request'),
    
    
    
    
    
    
    
    path('order/<uuid:pk>', views.OrderDetails.as_view(), name='order'), 
    path('order/project-interation/<uuid:pk>/<int:todo_id>/submit/', views.OrderDetails.as_view(), name='submit_interaction'), 
    path('order/project-interation/<uuid:pk>/<int:todo_id>/<int:interaction_id>/accept/', views.OrderDetails.as_view(), name='accept_reply'), 
    
    
    
    
    
    path('change_pass/', views.password_change, name='change_pass'),   
    path(
        "password_change/done/",
        views.CustomPasswordChangeDoneView.as_view(),
        name="password_change_done",
    ), 
    path('delete-avatar/', views.delete_avatar, name='delete_avatar'),  
]

cms/urls.py
from django.urls import path
from .views import *


app_name = 'cms'

urlpatterns = [   
    path('b/<str:slug>/', blog_detail, name='blog_details'),
    path('latest/blogs/', latest_blogs, name='latest_blogs'),       
    path('<str:username>/blogs/', user_blogs, name='user_blogs'), 
    # path('category/<str:slug>', category_detail, name='category_detail'),    
    # path('archive/<int:year>/<int:month>', archive_detail, name='archive_detail'),   
    path('p/<str:slug>', page_detail, name='page_detail'),   
    path('c/<int:blog_id>/<int:parent_id>', proccess_reply, name='proccess_reply'),   
    path('c/delete_reply/<int:parent_id>/<int:reply_id>', delete_reply, name='delete_reply'),  
    path('c/delete_comments/<int:blog_id>/<int:comment_id>', delete_comments, name='delete_comments'),   
     path('action/<int:content_type_id>/<int:obj_id>/<str:action>/', handle_action, name='handle_action'),
     

]

service/urls.py
from django.urls import path, include
from .views import *

app_name = 'service'

urlpatterns = [
    path('', ServiceList.as_view(), name='service_list'),
    path('<uuid:pk>/', ServiceDetailView.as_view(), name='service_details'),
    # path('collect-requirements/<uuid:order_id>/<uuid:pk1>/<uuid:pk2>/', CollectRequirements.as_view(), name='collect_requirements'),
    path('collect-order-info/<uuid:service_id>/<uuid:selected_price_id>/', CollectOrderInfo.as_view(), name='collect_order_info'),
    
    path('quotation-request/<uuid:pk>/', QuotationRequest.as_view(), name="quotation_request"),
    path('web-quotation/<uuid:pk>/', QuotationDetail.as_view(), name="web_quotation"),
    path('pdf-quotation/<uuid:pk>/', QuotationPDF.as_view(), name="pdf_quotation"),
    path('payment-success/', payment_success, name="payment_success"),
    path('payment-cancel/', payment_cancel, name="payment_cancel"),  
    path('update-payment/<uuid:id>', update_payment, name='update_payment'),  
    path('cancel-order/<uuid:id>', cancel_order, name='cancel_order'),  
    
    
    
]

service/views.py
from datetime import datetime
from django.utils import timezone
import random
import string
from django.forms import formset_factory, inlineformset_factory
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.generic import ListView
from accounts.models import User
from core.agent_helper import get_location_info
from core.context_processor import site_data
from core.helper import converted_amount, calculate_delivery_date, user_activities
from core.tasks import custom_send_mail_task
from core.templatetags.core import formatedprice, price_msg, title_and_price
from service.forms import  EmailCollectionForm, OrderFileForm, OrderImageForm, OrderTextForm, PaymentForm, PaymentGatewayForm, ServicePriceForm
from payment_method.gateways.base import PaymentGatewayBase
from .models import *
from django.views import View
from payment_method.gateways import active_payment_methods
import uuid
from payment_method.utils import get_payment_method_class
from django.contrib import messages
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
import io
from django.http import FileResponse, Http404, HttpResponse, HttpResponseRedirect
from core.templatetags.core import convert_amount, formatedprice, get_user_identity, remove_dash_hyphen_capital
from service.forms import ServicePriceForm
from service.decorators import quotation_creator_required
from service.forms import AcceptForm, QuotationForm, RejectForm
from django.contrib.auth.mixins import LoginRequiredMixin
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.units import inch

import logging
log =  logging.getLogger('log')

class ServiceList(ListView):
    model = Service
    template_name = 'service/service_list.html'  # Replace with your desired template path
    context_object_name = 'services'  # This sets the variable name in the template
    paginate_by = 10  # Number of services to display per page (you can change this as needed)
    ordering = '-updated_at'
    
    def get_queryset(self):
        selected_category_id = self.request.GET.get('q', None)

        if selected_category_id is not None:
            selected_category_id = uuid.UUID(selected_category_id)
            category_obj = get_object_or_404(ServiceCategory, pk=selected_category_id)
            services_queryset = category_obj.category_services.filter(is_active=True).prefetch_related(
                'service_images',
                'service_meta_data',
                'service_features',
                'prices_of_service',
            )
        else:
            services_queryset = Service.objects.filter(is_active=True).prefetch_related(
                'service_images',
                'service_meta_data',
                'service_features',
                'prices_of_service',
            )

        return services_queryset

    def get_context_data(self, **kwargs):
        context = super(ServiceList, self).get_context_data(**kwargs)
        site = site_data()
        site['title'] = 'Our Services'
        site['description'] = 'Discover our top-tier services: Web Development, ERP Solutions, Graphic Design, API Integration, Payment Gateways, eCommerce Development, and Monthly Retainers. Your digital success, our expertise.'
        context['site_data'] = site
        
        service_categories = ServiceCategory.objects.filter(is_active=True)        
        context['service_categories'] = service_categories
        
        selected_category_id = self.request.GET.get('q', None)           
        if selected_category_id is not None:
            category_id = uuid.UUID(selected_category_id)    
        else:    
            category_id = selected_category_id
            
        context['filters'] = {'q' : [category_id]}
        context['q'] = category_id
        
        if settings.SALING_SERVICE:
            return context
        else:
            raise Http404
    

def get_formatted_prices(service, currency):    
    return [formatedprice(price, currency) for price in service.prices_of_service.all()]


class ServiceDetailView(View):
    http_method_names = ['get', 'post']
    template_name = 'service/service_detail.html'
    
    @property
    def service_id(self):
        service_id = self.kwargs['pk']
        return service_id

    @property
    def get_service(self):   
        return get_object_or_404(Service.objects.prefetch_related('prices_of_service'), pk=self.service_id)
    
    @property
    def get_formated_price(self):
        formatted_prices = get_formatted_prices(self.get_service, self.request.currency)
        return formatted_prices
    
    
    @property
    def default_context(self):
        context = {}
        
        site = site_data()
        site['title'] = self.get_service.name
        site['description'] = self.get_service.description[:150]        
        
        context['site_data'] = site
        context['service'] = self.get_service
        
        
        return context         
        

    def get(self, *args, **kwargs):        
        context = self.default_context  
         
        price_option_form = ServicePriceForm(
            prices=self.get_service.prices_of_service.all(), 
            formatted_prices=self.get_formated_price
            )    
        
        
        context['form'] = price_option_form  
        
        if settings.SALING_SERVICE:
            return render(self.request, self.template_name, context)
        else:
            raise Http404

    def post(self, *args, **kwargs):
        if settings.SALING_SERVICE:
            pass
        else:
            raise Http404
        
        context = self.default_context   
        
        price_option_form = ServicePriceForm(
            prices=self.get_service.prices_of_service.all(), 
            formatted_prices=self.get_formated_price, 
            data=self.request.POST
            )                    
        if price_option_form.is_valid():
            selected_price_id =  uuid.UUID(price_option_form.cleaned_data['price_id'])     
            price_obj = Price.objects.get(id = selected_price_id)                   
            return HttpResponseRedirect(price_obj.resume_url)
        else:
            messages.warning(self.request, 'Select valid price options!')
            return render(self.request, self.template_name, context)
        
class CollectOrderInfo(View):
    http_method_names = ['get', 'post']
    template_name = 'service/collect_order_info.html' 
    
    @property
    def service_id(self):
        return self.kwargs['service_id']
    
    @property
    def service(self):
        obj = get_object_or_404(Service, pk=self.service_id)
        return obj
    
    @property
    def selected_price_id(self):
        return self.kwargs['selected_price_id']
    
    @property
    def price_obj(self):
        obj = get_object_or_404(Price, pk=self.selected_price_id)
        return obj
    
    
    def get_valid_payment_gateways(self, amount):
        
        location_data = get_location_info(self.request)
        
        ip = location_data.get('ip')    
        if ip == '127.0.0.1':
            user_country = 'BD'
        else:
            user_country = location_data.get('country')
            
        payment_gateways = {}
        for payment_method in active_payment_methods:
            
            if isinstance(payment_method, PaymentGatewayBase): 
                allowed_amount_min, allowed_amount_max, allowed_amount_any = payment_method.allowed_amount()
                allowed_countries, allowed_any_country = payment_method.allowed_countries()
                # Check if the order amount is within the allowed range
                if allowed_amount_min <= amount <= allowed_amount_max or allowed_amount_any:
                    # Check if the user is browsing from an allowed country
                    if user_country in allowed_countries or allowed_any_country:  
                        payment_gateways[payment_method.get_gateway_name()] = payment_method.get_help_text()
            
                
        return payment_gateways
    
    def get_formsets(self):
        # Create formsets for related models
        OrderTextFormSet = formset_factory(OrderTextForm, extra=1, max_num=12, can_delete=False)
        OrderFileFormSet = formset_factory(OrderFileForm, extra=1, max_num=3, can_delete=False)
        OrderImageFormSet = formset_factory(OrderImageForm, extra=1, max_num=3, can_delete=False)
   
        if self.request.method == 'GET':
            order_text_forms = OrderTextFormSet(self.request.POST or None, self.request.FILES or None, prefix='order_text')
            order_file_forms = OrderFileFormSet(self.request.POST or None, self.request.FILES or None, prefix='order_file')
            order_image_forms = OrderImageFormSet(self.request.POST or None, self.request.FILES or None, prefix='order_image')
            
        if self.request.method == 'POST':
            order_text_forms = OrderTextFormSet(self.request.POST, self.request.FILES, prefix='order_text')
            order_file_forms = OrderFileFormSet(self.request.POST, self.request.FILES, prefix='order_file')
            order_image_forms = OrderImageFormSet(self.request.POST, self.request.FILES, prefix='order_image')
        
        return order_text_forms, order_file_forms, order_image_forms
    
    @property
    def default_context(self):
        context = {}
        
        site = site_data()
        site['title'] = 'Share Your Service Requirements Before Proceeding to Payment'
        site['description'] = 'Tailor your service to perfection by sharing your specific requirements with us before you proceed to the payment gateway. Customize every detail to ensure your order aligns perfectly with your needs. Your satisfaction is our priority.'
        
   

templates/service/cancel.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load core %}
{% block adsencecode %} {% endblock %}
{% block extra_head %}

{% endblock %}   

{% block hero %}
{% endblock %}

{% block content %}

<!-- Start: Hero Banner -->
<section class="bg-sh-4th"><b class="text-nowrap text-uppercase text-start d-xl-flex justify-content-start align-items-start align-content-start justify-content-xl-start absolute-bold-16vw">cancelled</b>
    <div class="container-fluid h-100">
        <div class="alert alert-success" role="alert"><span><strong>Alert</strong> text.</span></div>
        <div class="row text-center d-flex justify-content-center align-items-center h-100">
            <div class="col-12 text-center d-sm-flex d-md-flex m-auto justify-content-md-start pt8pb3">
                <div class="text-center d-block align-content-center m-auto align-items-xl-center">
                    <h3 class="text-uppercase fw-bold text-center mb-3 h25vw target-element">order</h3>
                    <h3 class="text-uppercase fw-bold mb-3 h95vw">cancelled</h3>
                </div>
            </div>
        </div>
    </div>
</section><!-- End: Hero Banner -->
<section class="pt5pb5">
    <div class="container-fluid">
        <div class="row d-flex justify-content-center align-items-center">
            <div class="col-12 col-xl-8">
                <h2 class="display-1 text-center border-0 font-aldrich fs6vw">No Issues!</h2><a class="btn btn-warning btn-lg d-flex flex-fill justify-content-center m-auto font-aldrich fs-1 target-element" role="button" target="_blank" rel="nofollow">Resume Order Here</a>
            </div>
        </div>
        <div class="row d-flex justify-content-center align-items-center align-content-center">
            <div class="col-12 col-xl-8">
                <div class="card mt-5">
                    <div class="card-body font-aldrich">
                        <h4 class="card-title">If Everything Ok ......</h4>
                        <div class="row gx-2 gy-2 d-flex justify-content-center align-items-center">
                            <div class="col-12">
                                <div class="card"><button class="btn btn-success btn-lg font-aldrich fs-1 target-element" type="button">START FROM PAYMENT</button></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% comment %} <div class="error-area ptb--200 ptb_sm--60 ptb_md--80">
    <div class="container">
        <div class="row align-item-center">
            <div class="col-lg-12">
                <div class="error-inner">
                    <h1>ORDER CANCELLED!</h1>
                    <h2 class="title">NO ISSUE!</h2>
                    <p class="description"> You may continue form this url if you want to edit your provided information</p>
                    {% if order.price.is_service %}
                    <a class="btn-default" href="{% url 'shop:collect_requirements' order.id  order.price.service.pk  order.price.pk  %}">Continue From Order Information</a>
                    {% endif %}
                    {% if order.price.is_quotation %}
                    <a class="btn-default" href="{% url 'shop:collect_requirements' order.id  order.price.quotation.pk  order.price.pk  %}">Continue From Order Information</a>
                    {% endif %}
                    {% if order.gateway_payment_url %}
                    <p class="description"> Also you may start from payment page directly by clicking here:</p>
                    <a class="btn-default" href="{{order.gateway_payment_url}}">Go to direct payment</a>
                    {% endif %}                    

                    
                </div>
            </div>
        </div>
    </div>
</div> {% endcomment %}

{% endblock %}


{% comment %} {% block footer %}
    {% include 'layouts/footer.html' %}
{% endblock %} {% endcomment %}

templates/service/formated_price.html
<!-- rendering by template tag -->
<div class="card-title fs-3">{{ price_obj.name|upper }} - {{ symbol }}{{ amount }}</div>
{% if price_obj.price_type == 'one_time' %}
<div class="interval-text border-top border-bottom">Will be completed by {{ price_obj.interval_count }} {{ price_obj.interval }}</div>
{% endif %}

{% if price_obj.price_type == 'recurring' %}
<div class="interval-text border-top border-bottom">Per {{ price_obj.interval_count }} {{ price_obj.interval }} Price</div>
{% endif %}
<div class="card-text">{{ price_obj.features|safe }}</div>

templates/service/service_list.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load core %}
{% block extra_head %}

{% endblock %}   

{% block hero %}
{% endblock %}

{% block content %}

  <!-- Start: Hero Banner -->
  <section class="bg-sh-4th">
    <b class="text-nowrap text-uppercase text-start d-flex absolute-bold-18vw">services</b>
    <div class="container-fluid h-100">
        {% if messages %}                                      
            {% for message in messages %}        
            <div class="alert alert-warning" role="alert">
                <span>
                    <strong>Alert:</strong> {{ message }}.
                </span>
            </div>
            {% endfor %}  
        {% endif %}
        <div class="row text-center d-flex justify-content-center align-items-center h-100">
            <div class="col-12 text-center d-sm-flex d-md-flex m-auto justify-content-md-start pt10pb10">
                <div class="text-center d-block align-content-center m-auto align-items-xl-center">
                    <h3 class="text-uppercase fw-bold text-center mb-3 h25vw">ALL SERVICES</h3>
                    <h3 class="text-uppercase fw-bold mb-3 h55vw">HAS BEEN LISTED BELOW</h3>
                </div>
            </div>
        </div>
    </div>
</section><!-- End: Hero Banner -->
<!-- Start: Hero Banner -->
<section class="bg-sh-4th overflow-hidden">
    <!-- Start: Articles Cards -->
    <div class="container py-4 py-xl-5">
        <form id="service_category_form" method = 'get' action="{% url 'service:service_list' %}" class="text-center w-100 overflow-hidden">
            {% csrf_token %}
            <select 
            class="bg-transparent border rounded-pill border-2 border-danger form-select-lg target-element form-select-transparent" 
            name="q" id="service_category">
                <optgroup label="Service Categories">
                    {% for sc in service_categories %}
                    <option value="{{sc.id}}" {% if sc.id == q %} selected {% endif %}>{{sc.title}}</option>
                    {% endfor %}
                </optgroup>
            </select>
        </form>
        <div class="row gy-0 justify-content-center align-items-stretch">
            <div class="col-11 col-lg-10 px-0">
                <div class="row gx-2 gy-2">
                 
                    {% for service in services %}
                        {% if forloop.counter|divisibleby:2 %}
                            {% include 'includes/service_col.html' with service=service background="bg-transparent" %}                    
                        {% else %}
                            {% include 'includes/service_col.html' with service=service background="bg-light" %}                    
                        {% endif %}
                    {% endfor %}
                    
                    <div class="col">

                        {% include 'includes/pagination.html' with services=page_obj filters=filters %}
                       
                       
         
                    </div>
                </div>
            </div>
        </div>
    </div><!-- End: Articles Cards -->
</section><!-- End: Hero Banner -->







        {% endblock %}

        {% block extra_body %}   
        <script>
            $(document).ready(function() {              
                $('#service_category').change(function() {
                    $('#service_category_form').submit();             
                });

            });


        </script> 
        {% endblock %}

        

templates/service/success.html
{% extends "layouts/base.html" %}
{% block robotindex %} <meta name="robots" content="noindex">  {% endblock %}
{% block adsencecode %} {% endblock %}

{% load static %} 

{% block hero %}

{% endblock %}


 {% block content %}
  <!-- Start: Hero Banner -->
  <section class="bg-sh-4th"><b class="text-nowrap text-uppercase text-start d-xl-flex justify-content-start align-items-start align-content-start justify-content-xl-start absolute-bold-20vw">success</b>
    <div class="container-fluid h-100">
        {% if messages %}                                      
            {% for message in messages %}        
            <div class="alert alert-warning" role="alert">
                <span>
                    <strong>Alert:</strong> {{ message }}.
                </span>
            </div>
            {% endfor %}  
        {% endif %}
        <div class="row text-center d-flex justify-content-center align-items-center h-100">
            <div class="col-12 text-center d-sm-flex d-md-flex m-auto justify-content-md-start pt8pb3">
                <div class="text-center d-block align-content-center m-auto align-items-xl-center">
                    <h3 class="text-uppercase fw-bold text-center mb-3 h25vw">order #{{order.order_number}}</h3>
                    <h3 class="text-uppercase fw-bold mb-3 h55vw">placed successfully</h3>
                    <h4 class="text-primary">Status:<small class="fw-light"> {{ payment_status }} </small></h4>

                    <h4 class="text-primary">Order Amount:<small class="fw-light"> {{order.amount}} BDT</small></h4>
                </div>
            </div>
        </div>
    </div>
</section><!-- End: Hero Banner -->
<section class="pb5pt10 pt-0">
    <div class="container-fluid">
        <div class="row d-flex justify-content-center align-items-center">
            <div class="col-12 col-xl-8">
                <h2 class="display-1 text-center fs6vw font-aldrich rounded-3 border-light pt5pb5">Mail Sent</h2>
                <div class="card mt-3">
                    <div class="card-body font-alexandria">
                        <p class="card-text">{{gatway_instruction|safe}}</p>
                        
                        {{html_content|safe}}

                    </div>
                </div>
            </div>
        </div>
        <div class="row d-flex justify-content-center align-items-center align-content-center">
            <div class="col-12 col-xl-8">
                <div class="card mt-3">
                    <div class="card-body font-alexandria">
                        <h4 class="card-title">Helpful Navigations</h4>
                        <div class="row gx-2 gy-2 d-flex justify-content-center align-items-center">
                            <div class="col-12 col-md-6 col-lg-4">
                                <div class="card"><a class="btn btn-primary btn-lg font-atomic" href="{% url 'accounts:login' %}">LOGIN</a></div>
                            </div>
                            <div class="col-12 col-md-6 col-lg-4">
                                <div class="card"><a class="btn btn-primary btn-lg font-atomic" href="{% url 'service:service_list' %}">SERVICES</a></div>
                            </div>
                            <div class="col-12 col-md-6 col-lg-4">
                                <div class="card"><a class="btn btn-primary btn-lg font-atomic" href="{% url 'accounts:user_dashboard' %}">DASHBOARD</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

 {% endblock %}



{% comment %} {% block about %}

<div class="error-area ptb--200 ptb_sm--60 ptb_md--80">
    <div class="container">
        <div class="row align-item-center">
            <div class="col-lg-12">
                <div class="error-inner">
                    <h1>ORDER PLACED!</h1>
                    <h2 class="title">Successfully!</h2>
                    <p class="description"> Placed order reference is {{order.id}}! </p>
                    <p class="description"> Please check your order email! </p>
                    

                    <div class="view-more-button"><a class="btn-default" href="{% url 'accounts:login' %}">Login</a></div>                  
                    <div class="view-more-button"><a class="btn-default" href="{% url 'shop:service_list' %}">Explore Services</a></div>
                    <div class="view-more-button"><a class="btn-default" href="{% url 'accounts:user_dashboard' %}">Go To Dashboard</a></div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}


{% block footer %}
    {% include 'layouts/footer.html' %}
{% endblock %} {% endcomment %}