cms/urls.py
from django.urls import path
from .views import *


app_name = 'cms'

urlpatterns = [   
    path('b/<str:slug>/', blog_detail, name='blog_details'),
    path('latest/blogs/', latest_blogs, name='latest_blogs'),       
    path('<str:username>/blogs/', user_blogs, name='user_blogs'), 
    # path('category/<str:slug>', category_detail, name='category_detail'),    
    # path('archive/<int:year>/<int:month>', archive_detail, name='archive_detail'),   
    path('p/<str:slug>', page_detail, name='page_detail'),   
    path('c/<int:blog_id>/<int:parent_id>', proccess_reply, name='proccess_reply'),   
    path('c/delete_reply/<int:parent_id>/<int:reply_id>', delete_reply, name='delete_reply'),  
    path('c/delete_comments/<int:blog_id>/<int:comment_id>', delete_comments, name='delete_comments'),   
     path('action/<int:content_type_id>/<int:obj_id>/<str:action>/', handle_action, name='handle_action'),
     

]

core/urls.py
from django.urls import path, include
from .views import *
from django.contrib.sitemaps.views import sitemap
from .sitemaps import *
from django.views.generic.base import TemplateView

app_name = 'core'

sitemap_list = {
    'static': StaticSitemap,
    'pages' : PageSitemap,
    'category' : CategorySitemap,
    'blogs' : BlogSitemap,
    # 'whois' : WhoisSitemap
}

urlpatterns = [
    path('sitemap.xml', sitemap, {'sitemaps': sitemap_list}, name='django.contrib.sitemaps.views.sitemap'),      
    path('', home, name='home'),
    
]

service/urls.py
from django.urls import path, include
from .views import *

app_name = 'service'

urlpatterns = [
    path('', ServiceList.as_view(), name='service_list'),
    path('<uuid:pk>/', ServiceDetailView.as_view(), name='service_details'),
    # path('collect-requirements/<uuid:order_id>/<uuid:pk1>/<uuid:pk2>/', CollectRequirements.as_view(), name='collect_requirements'),
    path('collect-order-info/<uuid:service_id>/<uuid:selected_price_id>/', CollectOrderInfo.as_view(), name='collect_order_info'),
    
    path('quotation-request/<uuid:pk>/', QuotationRequest.as_view(), name="quotation_request"),
    path('web-quotation/<uuid:pk>/', QuotationDetail.as_view(), name="web_quotation"),
    path('pdf-quotation/<uuid:pk>/', QuotationPDF.as_view(), name="pdf_quotation"),
    path('payment-success/', payment_success, name="payment_success"),
    path('payment-cancel/', payment_cancel, name="payment_cancel"),  
    path('update-payment/<uuid:id>', update_payment, name='update_payment'),  
    path('cancel-order/<uuid:id>', cancel_order, name='cancel_order'),  
    
    
    
]

core/models.py
from django.db import models
from django.contrib.sites.models import Site
from django.core.validators import FileExtensionValidator
from django.contrib.sites.managers import CurrentSiteManager

from django.utils.translation import activate, gettext_lazy as _

from django.core.validators import FileExtensionValidator
from django.contrib.sites.models import Site






# Create your models here.
class ExSite(models.Model):    
    site = models.OneToOneField(Site, primary_key=True, verbose_name='site', on_delete=models.CASCADE)   
    site_description = models.TextField(max_length=500, null=True, blank=True)
    site_meta_tag =models.CharField(max_length=255, null=True, blank=True)
    site_favicon = models.ImageField(upload_to='site_image/', null=True, blank=True)
    site_logo = models.ImageField(upload_to='site_image/', null=True, blank=True)
    trademark = models.ImageField(upload_to='site_image/', null=True, blank=True)
    slogan = models.CharField(max_length=150, default='', null=True, blank=True)
    og_image = models.ImageField(upload_to='site_image/', null=True, blank=True)
    mask_icon = models.FileField(upload_to='site_image/', validators=[FileExtensionValidator(['svg'])], null=True, blank=True)    
    facebook_link = models.URLField(null=True, blank=True)
    twitter_link = models.URLField(null=True, blank=True)
    linkedin_link = models.URLField(null=True, blank=True)    
    instagram_link = models.URLField(null=True, blank=True)  
    
    email = models.EmailField(null=True, blank=True)
    location = models.TextField(null=True, blank=True)
    phone = models.CharField(max_length=16, null=True, blank=True)
    
    
    objects = models.Manager()
    on_site = CurrentSiteManager('site')
    
    def __str__(self):
        return self.site.__str__()  

core/views.py
from django.conf import settings
from django.shortcuts import render
from django.contrib import messages
from core.context_processor import site_data
from django.utils.html import strip_tags
from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from core.agent_helper import get_client_ip
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import random
from django.views.generic.edit import CreateView
from django.db.models import Count, Q
from core.helper import (
    custom_send_mail, 
    custom_send_mass_mail, 
    get_blogs,
    get_featured, 
    # get_services,
    get_service_categories,
    get_category_with_count,
    get_top_views,
    get_blog_archive
    )
from .models import *
from cms.models import *

from .forms import *
import calendar
from django.views.decorators.cache import cache_control

import logging
log =  logging.getLogger('log')


# Create your views here.

def home(request):
    template_name = 'core/home.html'    
        
    site = site_data()
    site['title'] = site.get('slogan')    
   
    latest_news = get_featured()

    about_us_link = get_object_or_404(Page, slug='about-us').get_absolute_url()
    
    service_categories = get_service_categories()  
    
    context = {    
        'site_data' : site,
        'latest_news' : latest_news,
        'about_us_link': about_us_link,
        'service_categories' : service_categories        
    }
    return render(request, template_name, context=context)





    



    

templates/core/home.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load core %}
{% load cache %}
 {% block content %}
 <!-- Start: About us sections -->
    <section class="section-bg-light"><b class="text-nowrap text-uppercase text-start d-xl-flex  target-element absolute-bold-18vw">ABOUT US</b>
        <div class="container-fluid h-100">
            <div class="row text-center d-flex justify-content-center align-items-center h-100">
                <div class="col-12 text-center d-flex m-auto pt-30-pb-5">
                    <div class="text-center d-block m-auto">
                        <h3 class="text-uppercase fw-bold text-center mb-3 h25vw">EMPOWRING</h3>
                        <h3 class="text-uppercase fw-bold mb-3 target-element h55vw">INNOVATIVE | QUALITY-DRIVEN </h3>
                        <p class="text-center mb-4 p3vw"> We shine through our commitment to customer happiness, innovation, and ethical business values.</p>
                        <a class="a3vw" href="{{about_us_link}}">About Us</a>
                    </div>
                </div>
                <div class="col-12 text-center d-flex justify-content-center m-auto pt5pt15">
                    {% cache 30000 time_less_sh %}
                    <img class="img-fluid text-center" loading="lazy" src="{% static 'assets/img/time_less_sh.png' %}" alt="SinceHence Timeless">
                    {% endcache %}
                </div>
            </div>
        </div>
    </section><!-- End: About us sections -->


    <!-- Start: Mission Section -->
    <section class="bg-dark"><b class="text-nowrap text-uppercase text-start text-secondary d-flex  absolute-bold-18vw">mission</b>
        <div class="container-fluid h-100">
            <div class="row text-center d-flex justify-content-center align-items-center h-100">
                <div class="col-12 text-center d-flex m-auto pt-30-pb-5">
                    <div class="text-center d-block align-content-center m-auto">
                        <h3 class="text-uppercase fw-bold text-center text-white mb-3 h25vw"><strong>
                            <span class="text-light">engage</span></strong></h3>
                        <h3 class="text-uppercase fw-bold text-white mb-3 h55vw target-element">enrich | foster</h3>
                        <p class="text-center text-white mb-4 p3vw"> Timeless Elegance Meets Modern Convenience</p>
                        <a class="link-light a3vw" href="{{about_us_link}}">Our Mission</a>
                    </div>
                </div>
                <div class="col-12 text-center d-flex justify-content-center align-self-center m-auto pt5pt15">
                    {% cache 30000 elegence %}
                    <img class="img-fluid d-flex justify-content-center align-items-center text-center" loading="lazy" src="{% static 'assets/img/elegence.png' %}">
                    {% endcache %}
                </div>
            </div>
        </div>
    </section><!-- End: Mission Section -->
    <!-- Start: Service Section -->
    <section class="bg-5th"><b class="text-nowrap text-uppercase text-start text-white d-flex  absolute-bold-18vw">services</b>
        <div class="container-fluid h-100">
            <div class="row text-center d-flex justify-content-center align-items-center h-100">
                <div class="col-12 text-center d-flex m-auto pt-30-pb-5">
                    <div class="text-center d-block align-content-center m-auto">
                        <h3 class="text-uppercase fw-bold text-center text-white mb-3 h25vw">Unparalleled</h3>
                        <h3 class="text-uppercase fw-bold text-white mb-3 h55vw target-element">Tailored to Your Needs</h3>
                        <p class="text-center text-white mb-4 p3vw"> From top-tier Amazon sales to expert IT consultancy, data processing, and wholesale trade </p>
                        <a class="link-light a3vw" href="{% url 'service:service_list' %}">Our Services</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- Start: Service Section  -->
        <div class="container py-4 py-xl-5">
            <div class="row gx-0 gy-0 pb15">

                {% with ratio_string="7:5:6:6:12" %}
                   
                        {% for category in service_categories %} 
                                <div class="col-12 col-lg-{% calculate_col_ratios forloop.counter ratio_string %} d-flex justify-content-center align-items-center border-2 target-element border border-3 border-secondary front-article" style="background: url({{ category.banner.url }}), var(--bs-primary);">
                                    <a href="{{ category.get_absolute_url }}" class="btn btn-info text-uppercase fs-6 fw-semibold hidden-button" type="button">View {{category.title}}</a>
                                    <div class="card bg-transparent border-0">
                                        <div class="card-body p-4">
                                            <h2 class="text-uppercase text-light card-title text-start">{{ category.title }}</h2>
                                            <p class="text-start text-light card-text mb-0">{{ category.description }}</p>
                                        </div>
                                    </div>
                                </div>
                        {% endfor %}
                  
                {% endwith %}
                
            </div>
        </div>
    </section><!-- End: Service Section -->
    <!-- Start: Hero Banner -->
    <section class="bg-danger"><b class="text-nowrap text-uppercase text-start text-white d-xl-flex  absolute-bold-18vw">articles</b>
        <div class="container-fluid h-100">
            <div class="row text-center d-flex justify-content-center align-items-center h-100">
                <div class="col-12 text-center d-sm-flex d-md-flex m-auto justify-content-md-start pt-30-pb-5">
                    <div class="text-center d-block align-content-center m-auto align-items-xl-center">
                        <h3 class="text-uppercase fw-bold text-center text-white mb-3 h25vw">News Hub</h3>
                        <h3 class="text-uppercase fw-bold text-white mb-3 target-element h55vw">Stay Informed!</h3>
                        <p class="text-center text-white mb-4 p3vw"> Stay connected and be the first to know! </p><a class="link-light a3vw" href="{% url 'cms:latest_blogs' %}">Latest Articles</a>
                    </div> 
                </div>
            </div>
        </div><!-- Start: Articles Cards -->
        <div class="container py-4 py-xl-5">
            <!-- Start: Articles_Sharma -->
            <div class="row gx-0 gy-0 pt5pt15 pt-0">
                {% with ratio_string="7:5:12" %}
                {% for news in latest_news %} 
                {% include 'includes/news.html' with news=news ratio_string=ratio_string border="border-danger" %}
                {% endfor %}
                {% endwith %}           
            </div><!-- End: Articles_Sharma -->
        </div><!-- End: Articles Cards -->
    </section><!-- End: Hero Banner -->
    {% endblock %}