accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, PasswordChangeDoneView 
from .forms import LoginForm
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('login/', views.CustomLoginView.as_view(redirect_authenticated_user=True, template_name='registration/login.html',  authentication_form=LoginForm), name='login'), 
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_reset/', views.CustomPasswordResetView.as_view(), name='password_reset'), 
    path("password_reset/done/",  views.CustomPasswordResetDoneView.as_view(), name="password_reset_done" ),
    path("reset/<uidb64>/<token>/", views.CustomPasswordResetConfirmView.as_view(),  name="password_reset_confirm" ),
    path("reset/done/", views.CustomPasswordResetCompleteView.as_view(),  name="password_reset_complete", ),
    path('activate/<uidb64>/<token>/',views.activate, name='activate'),   
    path('settings/', views.profile_setting, name='profile_setting'), 
    path('dashboard/', views.DashboardView.as_view(), name='user_dashboard'), 
    path('orders/', views.OrdersView.as_view(), name='user_orders'), 
    path('due-orders/', views.DueOrdersView.as_view(), name='due_orders'), 
    path('incomplete-orders/', views.IncompleteOrdersView.as_view(), name='incomplete_orders'), 
    
    path('projects/', views.DashboardView.as_view(), name='user_projects'), 
    path('recent-activities/', views.RecentActivityView.as_view(), name='user_recents_activity'), 
    path('recent-comments/', views.RecentCommentsView.as_view(), name='user_recents_comments'), 
    path('expert-profiles/', views.ExpertiseProfile.as_view(), name='expert_profiles'), 
    path('expert-profiles/<uuid:profile_id>/edit/', views.ExpertiseProfile.as_view(), name='edit_expert_profile'),
    path('expert-profiles/<uuid:profile_id>/delete/', views.ExpertiseProfile.as_view(), name='delete_expert_profile'),
    
    path('verification-request/', views.VerificationRequest.as_view(), name='verification_request'), 
    # path('verification/<uuid:verification_request_id>/<str:image_type>/', views.serve_image, name='serve_verification_image'),
    
    path('submit-approval-request/<uuid:profile_id>/', views.SubmitApprovalRequest.as_view(), name='submit_approval_request'),
    path('delete-approval-request/<uuid:profile_id>/<int:request_id>/delete', views.SubmitApprovalRequest.as_view(), name='delete_approval_request'),
    
    
    
    
    
    
    
    path('order/<uuid:pk>', views.OrderDetails.as_view(), name='order'), 
    path('order/project-interation/<uuid:pk>/<int:todo_id>/submit/', views.OrderDetails.as_view(), name='submit_interaction'), 
    path('order/project-interation/<uuid:pk>/<int:todo_id>/<int:interaction_id>/accept/', views.OrderDetails.as_view(), name='accept_reply'), 
    
    
    
    
    
    path('change_pass/', views.password_change, name='change_pass'),   
    path(
        "password_change/done/",
        views.CustomPasswordChangeDoneView.as_view(),
        name="password_change_done",
    ), 
    path('delete-avatar/', views.delete_avatar, name='delete_avatar'),  
]

cms/urls.py
from django.urls import path
from .views import *


app_name = 'cms'

urlpatterns = [   
    path('b/<str:slug>/', blog_detail, name='blog_details'),
    path('latest/blogs/', latest_blogs, name='latest_blogs'),       
    path('<str:username>/blogs/', user_blogs, name='user_blogs'), 
    # path('category/<str:slug>', category_detail, name='category_detail'),    
    # path('archive/<int:year>/<int:month>', archive_detail, name='archive_detail'),   
    path('p/<str:slug>', page_detail, name='page_detail'),   
    path('c/<int:blog_id>/<int:parent_id>', proccess_reply, name='proccess_reply'),   
    path('c/delete_reply/<int:parent_id>/<int:reply_id>', delete_reply, name='delete_reply'),  
    path('c/delete_comments/<int:blog_id>/<int:comment_id>', delete_comments, name='delete_comments'),   
     path('action/<int:content_type_id>/<int:obj_id>/<str:action>/', handle_action, name='handle_action'),
     

]

service/urls.py
from django.urls import path, include
from .views import *

app_name = 'service'

urlpatterns = [
    path('', ServiceList.as_view(), name='service_list'),
    path('<uuid:pk>/', ServiceDetailView.as_view(), name='service_details'),
    # path('collect-requirements/<uuid:order_id>/<uuid:pk1>/<uuid:pk2>/', CollectRequirements.as_view(), name='collect_requirements'),
    path('collect-order-info/<uuid:service_id>/<uuid:selected_price_id>/', CollectOrderInfo.as_view(), name='collect_order_info'),
    
    path('quotation-request/<uuid:pk>/', QuotationRequest.as_view(), name="quotation_request"),
    path('web-quotation/<uuid:pk>/', QuotationDetail.as_view(), name="web_quotation"),
    path('pdf-quotation/<uuid:pk>/', QuotationPDF.as_view(), name="pdf_quotation"),
    path('payment-success/', payment_success, name="payment_success"),
    path('payment-cancel/', payment_cancel, name="payment_cancel"),  
    path('update-payment/<uuid:id>', update_payment, name='update_payment'),  
    path('cancel-order/<uuid:id>', cancel_order, name='cancel_order'),  
    
    
    
]

templates/includes/meta.html
<title>{{ site_data.name }} -{% block head_title %}{{ site_data.title }}{% endblock %}</title> 
    <meta name="description" content="{{ site_data.description }}">
    <meta name="author" content="{{ site_data.author }}">
    <meta name="category" content="company"/>
    <meta name="theme-color" content="#960609">     


    <meta name="twitter:title" content="{{ site_data.name }} - {{ site_data.title }}">
    <meta name="twitter:card" content="summary">
    <meta name="twitter:image" content="{{ site_data.og_image }}">
    <meta property="twitter:description" content="{{ site_data.description }}">
    <meta property="twitter:url" content="{{ request.build_absolute_uri }}">
    <meta name="twitter:site" content="@sincehence" />
    <meta name="twitter:creator" content="@sincehence" /> 

    <meta property="og:title" content="{{ site_data.name }} - {{ site_data.title }}">
    <meta property="og:image" content="{{ site_data.og_image }}">
    <meta property="og:type" content="website">
    <meta property="og:description" content="{{ site_data.description }}">
    <meta property="og:url" content="{{ request.build_absolute_uri }}">
    <link rel="canonical" href="{{ request.build_absolute_uri }}">

    
    
    <link rel="icon" type="image/svg+xml" sizes="150x150" href="{{ site_data.mask_icon }}">
    <link rel="icon" type="image/svg+xml" sizes="150x150" href="{{ site_data.mask_icon }}" media="(prefers-color-scheme: dark)">
    <link rel="icon" type="image/svg+xml" sizes="150x150" href="{{ site_data.mask_icon }}">
    <link rel="icon" type="image/svg+xml" sizes="150x150" href="{{ site_data.mask_icon }}">
    <link rel="icon" type="image/png" sizes="2596x615" href="{{ site_data.site_logo }}">
    

    <link rel="manifest" href="{% url 'webmanifest' %}">

templates/includes/news.html
{% load static %}
{% load core %}


<div class="col-12 col-lg-{% calculate_col_ratios forloop.counter ratio_string %} d-flex home-article" data-bss-hover-animate="pulse">
    <div class="card border-3 {{border}} rounded-0 flex-fill">
        <img class="card-img-top w-100 d-block fit-cover h200p rounded-0 border-0" src="{{ news.feature.url }}" loading="lazy" />
        <div class="card-body d-flex flex-column justify-content-center align-items-start p-4">
            <p class="text-primary card-text mb-0 article-title">{{ news.title|truncatechars:13 }}</p>
            <h5 class="text-secondary card-title border-2 border-primary border-top border-bottom">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-c-square" viewBox="0 0 16 16">
                    <path d="M8.146 4.992c-1.212 0-1.927.92-1.927 2.502v1.06c0 1.571.703 2.462 1.927 2.462.979 0 1.641-.586 1.729-1.418h1.295v.093c-.1 1.448-1.354 2.467-3.03 2.467-2.091 0-3.269-1.336-3.269-3.603V7.482c0-2.261 1.201-3.638 3.27-3.638 1.681 0 2.935 1.054 3.029 2.572v.088H9.875c-.088-.879-.768-1.512-1.729-1.512Z"/>
                    <path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2Zm15 0a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2Z"/>
                    </svg>
                     {{ news.creator.get_full_name }} 
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-calendar-check" viewBox="0 0 16 16">
                    <path d="M10.854 7.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7.5 9.793l2.646-2.647a.5.5 0 0 1 .708 0z"/>
                    <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4H1z"/>
                    </svg>
                     {{ news.created_at.date }} </h5>
            <p class="fs-5 card-text">{{ news.body|safe|truncatechars:130 }}</p>
            <div class="border-top border-bottom border-2 border-primary pb-1 mb-2">
                {% for cat in news.categories.all %}
                
                <a href="{{ cat.get_absolute_url }}" class="badge bg-secondary me-2">{{ cat.title }}</a>
                {% endfor %}
                
            </div>
            <a class="btn btn-primary align-self-end target-element" href="{{ news.get_absolute_url }}">Read Article</a>
        </div>
    </div>
</div>

templates/includes/offcanvas_body_left.html
{% load static %}
<div>
    <hr class="mt-0">
    <ul class="nav nav-pills flex-column mb-auto">
        {% for menu in dashnoard_menu %}
        <li class="nav-item fs2vw">
            <a class="nav-link link-primary d-flex align-items-lg-center px-2 {% if menu.url == request.path %}active link-light{% endif %}" href="{{menu.url}}" aria-current="page">
                {{menu.icon|safe}}
                {{menu.title}}
            </a>
        </li>
        {% endfor %}
       
    </ul>
</div>
<div>
    <hr>
    <div class="dropdown">
        <a class="dropdown-toggle link-body-emphasis d-flex align-items-center text-decoration-none" aria-expanded="false" data-bs-toggle="dropdown" role="button">
            <img class="rounded-circle me-2" alt="" width="32" height="32" src="{% if request.user.is_authenticated %}{{request.user.avatar}}{% else %}{% static 'no_image.png' %}{% endif %}" style="object-fit: cover;">
            <strong>{% if request.user.firstname %}{{request.user.firstname}}{% else %}Set Profile{% endif %}</strong>&nbsp;
        </a>
        <div class="dropdown-menu shadow text-small" data-popper-placement="top-start">
            {% for um in user_menu %} 
            {% for uml in um.data_set %} 
            <a class="dropdown-item" href="{{uml.url}}">{{uml.title}}</a>
            {% endfor %}
            {% endfor %}

            {% comment %} <a class="dropdown-item" href="#">Account Settings</a>
            <a class="dropdown-item" href="{% url 'accounts:change_pass' %}">Change Password</a> {% endcomment %}
            {% comment %} <div class="dropdown-divider"></div> {% endcomment %}
            {% comment %} <a class="dropdown-item" href="#">Sign out</a> {% endcomment %}
        </div>
    </div>
</div>

templates/includes/pagination.html
{% load core %}

{% if page_obj.has_other_pages %}
<nav class="p-3 px-0">
<ul class="pagination {% if pagination_class %} {{pagination_class}} {% else %} pagination-lg {% endif %}">
  {% if page_obj.has_previous %}
    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}{% for key, values in filters.items %}&{{ key }}={% for value in values %}{{ value }}{% endfor %}{% endfor %}">&laquo;</a></li>
  {% else %}
    <li class="disabled page-item"><span class="page-link">&laquo;</span></li>
  {% endif %}

  
  {% for i in page_obj.paginator.page_range %}
      {% if i == 1 %}
        <li class="page-item"><a class="page-link" href="?page=1{% for key, values in filters.items %}&{{ key }}={% for value in values %}{{ value }}{% endfor %}{% endfor %}">1</a></li>
      {% elif i == page_obj.number %}
        <li class="active page-item"><span class="page-link">{{ i }}</span></li>
      {% elif i > page_obj.number|add:'-3' and i < page_obj.number|add:'3' %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}{% for key, values in filters.items %}&{{ key }}={% for value in values %}{{ value }}{% endfor %}{% endfor %}">{{ i }}</a></li>
      {% elif i == page_obj.paginator.num_pages %}
        <li class="disabled page-item"><span class="page-link">&hellip;</span></li>
      {% endif %}
    {% endfor %}


  {% if page_obj.has_next %}
    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}{% for key, values in filters.items %}&{{ key }}={% for value in values %}{{ value }}{% endfor %}{% endfor %}">&raquo;</a></li>
  {% else %}
    <li class="disabled page-item"><span class="page-link">&raquo;</span></li>
  {% endif %}
</ul>
</nav>
{% endif %}

templates/includes/recent_and_howto.html
{% load humanizelib %}
{% if latest_activities %}
<div>
    <div class="d-flex justify-content-between align-items-end pt-3">
        <h2 class="text-primary">Recent Activity</h2>
        <a class="fs-5 text-decoration-none" href="{% url 'accounts:user_recents_activity' %}">View All</a>
    </div>
    <hr class="my-0">
    <div class="list-group list-group-flush border-bottom scrollarea">
        {% for activity in latest_activities %}
        <a class="list-group-item list-group-item-action py-3 lh-tight" href="{{activity.path}}" aria-current="true">
            <div class="d-flex justify-content-between align-items-center w-100">
                <b class="fs-5 mb-1">{{activity}}</b>
                <small class="fs-6">{{activity.timestamp|naturaltime}}</small>
            </div>
            <small class="fs-6">{{ activity.description|truncatechars:250 }}</small>
        </a>
        {% endfor %}
        
    </div>
</div>
{% endif %}
<div class="pt-3">
    <div>
        <h2 class="text-primary">How To</h2>
    </div>
    <div>
        <hr class="my-0">
        <div class="list-group list-group-flush border-bottom scrollarea"><a class="list-group-item list-group-item-action py-3 lh-tight" href="#" aria-current="true">
                <div class="d-flex justify-content-between align-items-center w-100"><b class="fs-6 mb-1">Payment Related</b></div>
            </a><a class="list-group-item list-group-item-action py-3 lh-tight" href="#" aria-current="true">
                <div class="d-flex justify-content-between align-items-center w-100"><b class="fs-6 mb-1">Execution Related</b></div>
            </a><a class="list-group-item list-group-item-action py-3 lh-tight" href="#" aria-current="true">
                <div class="d-flex justify-content-between align-items-center w-100"><b class="fs-6 mb-1">Support Related</b></div>
            </a><a class="list-group-item list-group-item-action py-3 lh-tight" href="#" aria-current="true">
                <div class="d-flex justify-content-between align-items-center w-100"><b class="fs-6 mb-1">Service related</b></div>
            </a></div>
    </div>
</div>

templates/includes/scripts.html
{% load static %}

<script src="{% static 'assets/js/jquery.min.js' %}"></script>
<script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/js/bootstrap-datepicker.min.js' %}"></script>    
<script src="{% static 'assets/js/bs-init.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/select2.full.min.js' %}"></script> 
<script src="{% static 'assets/htmx/dist/htmx.min.js' %}"></script>
<script src="{% static 'assets/js/index.global.min.js' %}"></script>





<script src="{% static 'assets/js/sincehence.js' %}"></script>

templates/includes/service_col.html
{% load core %}
<div class="col-12">
    <div class="card border-light border rounded-0 border-5 border-light {{background}}">
        <h1 class="text-capitalize text-start font-atomic fs6vw">{{ service.name }}</h1>
        <div class="card-body p-4">
            <p class="text-capitalize text-primary card-text mb-0 font-aldrich fs3vw">{{ service|get_meta_service_type }}</p>
            <h4 class="text-capitalize card-title fs3vw font-alexandria mb-3 mt28p text-dark">Available options to select:</h4>
             
                {% with form=service|get_price_option_form:request %}
                    <form class="row g-2 fs-5 text-start" action="{% url 'service:service_details' service.pk %}" method="POST">
                        {% csrf_token %}                 
                        {% for price_id, formatted_price in form.price_id.field.choices %}
                        <div class="d-flex col-12 col-lg-6 service-price">
                            <div class="flex-fill card gradient-card pe-4 ps-2 border-0 rounded-0">
                           
                                    <input class="{{ form.price_id.field.widget.attrs.class }}" type="radio" name="{{ form.price_id.name }}" id="price_{{ price_id }}" value="{{ price_id }}"{% if forloop.first %} checked {% endif %}>
                                    <label class="form-check-label text-start" for="price_{{ price_id }}">
                                        {{ formatted_price|safe }}
                                    </label>
                          
                            </div>
                        </div>                                
                        {% endfor %}                                                 
              
                        <div class="row gy-2 m-auto">
                            <div class="col-6">
                                <a href="{{ service.get_absolute_url }}" class="btn btn-secondary btn-lg d-flex flex-fill justify-content-center align-items-center align-content-stretch flex-nowrap font-aldrich" role="button">Read More</a>
                            </div>
                            <div class="col-6">                                           
                                <input class="btn btn-primary btn-lg d-flex flex-fill justify-content-center align-items-center align-content-stretch flex-nowrap font-aldrich w-100" type="submit" value="Start Order">  
                            </div>
                            <div class="col-12">
                                <a  href="{% url 'service:quotation_request' service.pk %}" class="btn btn-warning btn-lg d-flex flex-fill justify-content-center align-items-center align-content-stretch flex-nowrap font-aldrich" role="button" >Custom Quotation</a>                                
                            </div>
                        </div>                            
                    </form>
                {% endwith %}
                {% if form.errors %}
                    <div class="row gy-2 justify-content-evenly align-items-stretch mt-3">
                        <div class="alert alert-danger">
                            <strong>Errors:</strong>
                            <ul>
                                {% for field_name, errors in form.errors.items %}
                                    {% for error in errors %}
                                        <li>{{ error }}</li>
                                    {% endfor %}
                                {% endfor %}
                            </ul>
                        </div>                                
                    </div>
                {% endif %}
        
                
        </div>
    </div>
</div>